apiVersion: batch/v1
kind: Job
metadata:
  name: maison-epouvante-back-migrate
  namespace: maison-epouvante
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        fsGroup: 33
      containers:
        - name: migrate
          image: ghcr.io/etho01/maison-epouvante-back:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 33
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: maison-epouvante-back-secret
          command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction"]