name: PR 

on:
  pull_request:
    branches: [ main ]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml
        
    security-scan:
        uses: ./.github/workflows/security-scan.yml
        permissions:
            security-events: write
            contents: read
            actions: read

    test:
        needs: [code-quality, security-scan]
        uses: ./.github/workflows/test.yml